# Generated by Django 4.0.5 on 2022-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miasta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='citizens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='informations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
